apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      run: app
  template:
    metadata:
      labels:
        run: app
    spec:
      containers:
        - name: app1
          image: ubuntu:16.04
          tty: true
          volumeMounts:
            - name: my-configmap
              mountPath: /my-config-path
      volumes:
        - name: my-configmap 
          configMap:
            name: my-config
